/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vprogramcompiler;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        LineByLine classUnderTest = new LineByLine();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
